<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

            DB::table('articles')->insert([
            'category_id' => 1,
            'title' => '15 Tips on How to Brand Yourself',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => '15-tips-on-how-to-brand-yourself',
            'image' => 'uploads/1.jpg',
            'created_at' => now(),
            'updated_at' => now(),
            ]);

        DB::table('articles')->insert([
            'category_id' => 2,
            'title' => 'Quick Tips for Google Posts',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'quick-tips-for-google-posts',
            'image' => 'uploads/2.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' => 3,
            'title' => 'How to Make Newsworthy Content',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'how-to-make-newsworthy-content',
            'image' => 'uploads/3.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' => 4,
            'title' => '7 Tips to Get the Most Out of Online Conferences',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => '7-tips-to-get-the-most-out-of-online-conferences',
            'image' => 'uploads/4.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>5,
            'title' => 'Technical Seo Skills',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'technical-seo-skills',
            'image' => 'uploads/5.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>6,
            'title' => 'Free Google Tools to Upgrade Your SEO Strategy',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'free-google-tools-to-upgrade-your-seo-strategy',
            'image' => 'uploads/6.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>1,
            'title' => 'Free Google Tools to Upgrade Your SEO Strategy',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'free-google-tools-to-upgrade-your-seo-strategy',
            'image' => 'uploads/7.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>2,
            'title' => 'Smart Tips to Reduce Bounce Rate',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'smart-tips-to-reduce-bounce-rate',
            'image' => 'uploads/8.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>3,
            'title' => 'Can We Predict Anything About 2021?',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'can-we-predict-anyting-about-2021',
            'image' => 'uploads/9.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>4,
            'title' => 'Experts Weigh in on Industry-Specific Tactics',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'experts-weigh-in-on-industry-specific-tactics',
            'image' => 'uploads/10.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>5,
            'title' => 'Avoiding False Conversions in Google Analytics',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'avoiding-false-conversions-in-google-analytics',
            'image' => 'uploads/11.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>6,
            'title' => 'How to Create a Useful FAQ Page',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'how-to-create-a-useful-faq-page',
            'image' => 'uploads/12.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('articles')->insert([
            'category_id' =>1,
            'title' => 'Potential Measures of Authoritative Content',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime doloremque nobis cupiditate porro repudiandae laborum omnis! Voluptatem deserunt laudantium molestias nisi error, possimus porro distinctio cupiditate esse quia iure natus, repellat beatae, eius, dolorem totam ut sequi soluta ullam voluptate! Vero repudiandae consequatur laudantium voluptates amet quasi perferendis cumque earum est eos dicta, rerum magni rem cum, totam eum magnam voluptatibus ad. dolores sapiente nisi. Quisquam error dolorum nam porro temporibus numquam culpa nulla, consectetur autem. Neque dolor recusandae non maxime iure ipsam sequi, iste quibusdam aperiam adipisci reiciendis dicta debitis veniam distinctio praesentium repellendus quos quasi ullam vero eaque aspernatur, perspiciatis nemo. Ducimus eaque magni qui, quis iure inventore nobis quam doloremque minus enim, quas repudiandae distinctio! Quod dignissimos quaerat sed unde repudiandae, hic eveniet dolore. Harum quidem, vitae at quis magnam culpa repudiandae ex blanditiis nam. Cupiditate aperiam, quia dolores. Veritatis, aspernatur nulla provident perspiciatis modi iste quos alias laboriosam! Delectus possimus amet inventore, et explicabo non. Libero omnis quasi officia. accusantium, quas dolorum, qui fugit sint incidunt excepturi impedit distinctio eligendi inventore ad, ipsa non debitis ratione. Quaerat facere aliquam quisquam, quia maiores expedita est ut quis. Doloribus sint voluptatibus temporibus, numquam autem impedit ad qui optio cumque eos illo quaerat ullam corrupti veritatis blanditiis. Reiciendis alias quis repudiandae ipsum ut itaque autem numquam, tempore quisquam! Maxime in pariatur, autem dolorum, quam id provident, repudiandae impedit voluptate et illo ratione voluptas necessitatibus ducimus aut harum cumque obcaecati enim? Quas, error iste debitis suscipit assumenda earum ipsam expedita consectetur sit velit blanditiis aperiam, consequuntur nobis cum. Voluptatem soluta magnam adipisci recusandae inventore, modi, numquam facere accusamus maiores dicta commodi expedita provident placeat, rerum laboriosam repudiandae reprehenderit suscipit quidem et maxime vitae voluptas vel neque aliquam voluptatum! Fugit natus, quidem veritatis mollitia, reprehenderit illum temporibus similique a enim distinctio nobis harum soluta optio explicabo, officiis quaerat quia neque totam provident blanditiis incidunt fuga. Temporibus libero, voluptatem, alias, illum soluta magnam porro sit eos . repellat aspernatur saepe rem mollitia eligendi! Ducimus consequatur soluta unde voluptatum officiis veniam odit saepe ex, itaque, fuga quibusdam nesciunt. Omnis sapiente iusto, consequatur. Ea, recusandae.',
            'slug' => 'potential-measures-of-authoritative-content',
            'image' => 'uploads/13.jpg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

    }
}
